### PR TITLE
actions: Push without using external action

### PR DESCRIPTION
**Pull request by davidmhewitt**
This should work and removes a deprecated Node 12 action

### CODE REVIEW

**Review by RMcNeely — COMMENTED** [review]
Does this not require a token anymore to commit files?

**Comment by davidmhewitt** [comment]
Ah, well spotted! This would be able to push to the repo, but the GitHub action to deploy the site afterwards wouldn't run, because actions don't run on commits triggered by the default token (to prevent infinite loops). 

I've updated this to use the token with the `checkout` action, which it will use for the `push` command too.

**Comment by RMcNeely** [comment]
> Ah, well spotted! This would be able to push to the repo, but the GitHub action to deploy the site afterwards wouldn't run, because actions don't run on commits triggered by the default token (to prevent infinite loops). 
> 
> I've updated this to use the token with the `checkout` action, which it will use for the `push` command too.

Does this mean that we would need to manually deploy the updates after they are committed if they do not run on commits triggered by the default token? Or is that why we are now providing the token instead of using the default token used by checkout v3

**Comment by davidmhewitt** [comment]
> Or is that why we are now providing the token instead of using the default token used by checkout v3

Yes, this should work as before now.

You can see here where we push commits with the elementaryBot token that GitHub actions still run as a result of the pushes:
https://github.com/elementary/browser/pull/101

**Pull request merged**
